feat: Project covered by language toggle and documentation
gustavop-dev/projectapp pull request #2
Opened 2024-08-25 22:57 UTC by gustavop-dev

# Description

This Pull Request includes the following changes:

1. **Full Documentation Coverage**:
   - Complete documentation was added for all components, stores, utilities, and composables in the frontend project.
   - Each function, prop, and logic implementation is now documented, following best practices to ensure clarity and maintainability.

2. **Language Toggle Implementation**:
   - A language toggle has been implemented throughout the entire frontend project.
   - The user can now switch between supported languages (e.g., English and Spanish) dynamically.
   - All text content, including navigation links, buttons, and labels, now reflects the selected language, ensuring a consistent multilingual experience.
   - The global language store was updated to manage language changes across views and components efficiently.

# Changes
- Documented components, composables, and utilities.
- Implemented language toggle functionality.
- Updated the language store to handle dynamic text changes across the entire application.

# Additional Information
- No breaking changes introduced.
- The language toggle supports both English and Spanish, and additional languages can be easily integrated if needed.

2024-08-25 23:01 UTC, gustavop-dev commented
In prices.vue and hosting.vue belonging to views in frontend, you won't find documentation because these files are subject to changes.

2024-09-04 00:35 UTC, carlos18bp requested changes
frontend/src/views/hosting.vue
1. El nombre del componente deberia empezar con mayuscula
2. Linea 87,88,89,90 no terminan en ;
3. Agrega un espacio entre la linea 82 y 83
4. Barrer el template y cambiar las lineas demasiado largas

frontend/src/views/Prices.vue
1. Agrega un espacio entre la linea 408 y 409

frontend/src/views/Home.vue
1. Linea 71 no termina en ;

frontend/src/views/AboutUs.vue
1. Barrer el template y cambiar las lineas demasiado largas
2. Agrega un espacio entre la linea 76 y 77

frontend/src/views/3dAnimations/List.vue
1. Linea 51 no terminan en ;

frontend/src/components/Home/InitialVideo.vue
1. Barrer el template y cambiar las lineas demasiado largas

frontend/src/components/Layouts/Contact.vue
1. Barrer el template y cambiar las lineas demasiado largas

frontend/src/components/Layouts/Footer.vue
1. Barrer el template y cambiar las lineas demasiado largas
2. Extra line in line 110

frontend/src/components/Layouts/Navbar.vue
1. Barrer el template y cambiar las lineas demasiado largas

frontend/src/components/Utils/ButtonWithArrow.vue
1. En la linea 16 cuando uses querySelector la clase debe inicar con js-{name-clase}, 
Esto con el fin de saber que no es una clase css sino js

frontend/src/components/Utils/SocialLinks.vue
1. En la linea 26 cuando uses querySelector la clase debe inicar con js-{name-clase}, 
Esto con el fin de saber que no es una clase css sino js

frontend/src/components/spline/Backgrounds/Dune.vue
1. Arreglar la sangria

projectapp/content/__pycache__/serializers.cpython-312.pyc
projectapp/content/__pycache__/views.cpython-312.pyc
projectapp/content/models/__pycache__/__init__.cpython-312.pyc
projectapp/content/models/__pycache__/components.cpython-312.pyc
projectapp/content/models/__pycache__/contact.cpython-312.pyc
projectapp/content/models/__pycache__/designs.cpython-312.pyc
projectapp/content/models/__pycache__/models_3d.cpython-312.pyc
1. Esto no deberia estar en el repositorio, ni en tu pr, asegurate que tu .gitignore este bien configurado


Comentarios generales:
1. Todos los comentarios anteriores son de la rama main
2. Seria bueno agregar algunos comentarios dentro de la logica de los template, para saber que se esta haciendo
3. Los metodos no se encuentran documentados
4. En los serializadores de Django, si deseas incluir todos los campos del modelo en tu serializador, puedes utilizar la opción '__all__' en el atributo fields.
4. Una vez se atiendan los comentarios y todo este en la rama main, favor listarme las tareas que se me asignaran

2024-09-08 23:19 UTC, carlos18bp requested changes

2024-09-08 23:19 UTC, carlos18bp commented on frontend/src/components/Layouts/Contact.vue
> +                        <span ref="arrow" class="absolute right-0 top-1/2 transform -translate-y-1/2 opacity-0 transition-opacity duration-300">➜</span>
Line too large

2024-09-08 23:19 UTC, carlos18bp commented on frontend/src/components/Layouts/Contact.vue
> +                        <span ref="underline" class="absolute left-0 bottom-0 h-0.5 w-0 bg-black transition-all duration-300"></span>
Line too large

2024-09-08 23:19 UTC, carlos18bp commented on frontend/src/components/Layouts/Contact.vue
> +                        <span ref="underlineChat" class="absolute left-0 bottom-0 h-0.5 w-0 bg-black transition-all duration-300"></span>
Line too large

2024-09-08 23:19 UTC, carlos18bp commented on frontend/src/components/Layouts/Contact.vue
> +                        <span ref="arrowChat" class="absolute right-0 top-1/2 transform -translate-y-1/2 opacity-0 transition-opacity duration-300">➜</span>
Line too large

2024-09-08 23:19 UTC, carlos18bp commented on projectapp/content/serializers.py
> +        fields = "__all__"
Use single quotes here: `'__all__'`

2024-09-08 23:19 UTC, carlos18bp commented on projectapp/content/serializers.py
> +        fields = "__all__"
Use single quotes here: `'__all__'`

2024-09-08 23:19 UTC, carlos18bp commented on projectapp/content/serializers.py
> +        fields = "__all__"
Use single quotes here: `'__all__'`

2024-09-08 23:19 UTC, carlos18bp commented on projectapp/content/serializers.py
> +        fields = "__all__"
Use single quotes here: `'__all__'`

2024-09-08 23:19 UTC, carlos18bp commented on projectapp/content/serializers.py
> +        fields = "__all__"
Use single quotes here: `'__all__'`

2024-09-08 23:19 UTC, carlos18bp commented on projectapp/content/serializers.py
> +        fields = "__all__"
Use single quotes here: `'__all__'`

2024-09-08 23:19 UTC, carlos18bp commented on projectapp/content/serializers.py
> +        fields = "__all__"
Use single quotes here: `'__all__'`

2024-09-08 23:24 UTC, gustavop-dev commented on projectapp/content/serializers.py
> +        fields = "__all__"
Done!

2024-09-08 23:25 UTC, gustavop-dev commented on projectapp/content/serializers.py
> +        fields = "__all__"
Done

2024-09-08 23:25 UTC, gustavop-dev commented on projectapp/content/serializers.py
> +        fields = "__all__"
Done

2024-09-08 23:25 UTC, gustavop-dev commented on projectapp/content/serializers.py
> +        fields = "__all__"
Done

2024-09-08 23:25 UTC, gustavop-dev commented on projectapp/content/serializers.py
> +        fields = "__all__"
Done!

2024-09-08 23:25 UTC, gustavop-dev commented on projectapp/content/serializers.py
> +        fields = "__all__"
Done

2024-09-08 23:25 UTC, gustavop-dev commented on frontend/src/components/Layouts/Contact.vue
> +                        <span ref="arrow" class="absolute right-0 top-1/2 transform -translate-y-1/2 opacity-0 transition-opacity duration-300">➜</span>
Done

2024-09-08 23:25 UTC, gustavop-dev commented on frontend/src/components/Layouts/Contact.vue
> +                        <span ref="underline" class="absolute left-0 bottom-0 h-0.5 w-0 bg-black transition-all duration-300"></span>
Done

2024-09-08 23:26 UTC, gustavop-dev commented on frontend/src/components/Layouts/Contact.vue
> +                        <span ref="underlineChat" class="absolute left-0 bottom-0 h-0.5 w-0 bg-black transition-all duration-300"></span>
Done

2024-09-08 23:26 UTC, gustavop-dev commented on frontend/src/components/Layouts/Contact.vue
> +                        <span ref="arrowChat" class="absolute right-0 top-1/2 transform -translate-y-1/2 opacity-0 transition-opacity duration-300">➜</span>
Done

2024-09-08 23:56 UTC, carlos18bp approved these changes

2024-09-11 01:22 UTC, merged